### ISSUE TITLE
Readme install snippet points to Justineo's package

### ISSUE THREAD

**Issue by adi518** [BaglerIT/vue-octicons#5]
This package is registered at npm as `vue-octicons`, while the readme says `vue-octicon`, which is Justineo's package. This leads to consumers to install the wrong package. That's a critical mistake.

This also doesn't make sense:
```js
Vue.component('octicon', require('vue-octicons/src/components/Octicon.vue'));
```

**Comment by DaveBagler** [comment]
I've updated the readme.  What doesn't make sense in 
```js
Vue.component('octicon', require('vue-octicons/src/components/Octicon.vue'));
```
Is it not working for you? Please provide a PR if you're suggesting an alternative.

**Comment by adi518** [comment]
It doesn't make sense because it's going directly to the source inside `node_modules`. In the case of javascript, `node_modules` packages are expected to be transpiled to es5, namely what you have in your dist. Consuming should always be from the `main` entry in `package.json` and nothing else. There are exceptions, but this is the standard way of publishing and consuming.

**Comment by DaveBagler** [comment]
Thanks for the follow-up, @adi518, a PR is welcome.

**Comment by DaveBagler** [comment]
Closing.
